events { }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    server {
        listen 80;
        server_name ryban.ru www.ryban.ru;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name ryban.ru www.ryban.ru;

        ssl_certificate     /etc/nginx/certs/fullchain.crt;
        ssl_certificate_key /etc/nginx/certs/certificate.key;

        root /usr/share/nginx/html;
        index index.html;


        location /femboy/ {
            proxy_pass http://89.109.16.50:1986;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /femboyapi/ {
            proxy_pass http://89.109.16.50:1985;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://89.109.16.50:911;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}