events { }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        server_name ryban.ru www.ryban.ru;
        return 301 https://ryban.ru$request_uri;
    }

    server {
        listen 443 ssl;
        server_name ryban.ru;

        root /usr/share/nginx/html;
        index index.html;

        ssl_certificate     /etc/nginx/certs/ryban.ru.crt;
        ssl_certificate_key /etc/nginx/certs/ryban.ru.key;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;
        keepalive_timeout 70;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_stapling on;
        ssl_trusted_certificate /etc/nginx/certs/ca.crt;

        resolver 8.8.8.8;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /public/ {
            try_files $uri =404;
        }

        location /api/ {
            proxy_pass http://89.109.16.50:85;  # ← no trailing slash
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}